{{- if not .Values.staging }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        webhook:
          groupName: acme.namecheap.com
          solverName: namecheap
          config:
            apiKeySecretRef:
              name: {{ .Values.secret }}
              key: apiKey
            apiUserSecretRef:
              name: {{ .Values.secret }}
              key: apiUser
{{- end }}
