name: Tests

on:
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: make build

  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check spelling
      uses: crate-ci/typos@v1.0.4
